data_generator:
    output_dir: data/large
    entities:
        product:
            count: 2000000
            filled_attributes_count: 112
            filled_attributes_standard_deviation: 10
            mandatory_attributes: [sku, name]
            delimiter: ;
            start_index: 0
            categories_count: 4

