data_generator:
    output_dir: data/small/
    entities:
        product:
            count: 5000
            filled_attributes_count: 38
            filled_attributes_standard_deviation: 10
            mandatory_attributes: [sku, name]
            delimiter: ;
            start_index: 0
            categories_count: 2
